"""favorite feeds

Revision ID: 0ffba70d9aff
Revises: ca24c8f1c6b1
Create Date: 2025-03-13 14:17:50.317598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ffba70d9aff'
down_revision: Union[str, None] = 'ca24c8f1c6b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
