"""Add feed etag and modified

Revision ID: 228e12cf8426
Revises: f843d25ac6b0
Create Date: 2025-02-05 23:43:47.433720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '228e12cf8426'
down_revision: Union[str, None] = 'f843d25ac6b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('modified', sa.String(), nullable=True))
    op.add_column('feeds', sa.Column('etag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feeds', 'etag')
    op.drop_column('feeds', 'modified')
    # ### end Alembic commands ###
