"""channel cat delete

Revision ID: 30dc2b7d88e5
Revises: 9dd4c958be21
Create Date: 2025-03-13 18:12:10.763848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30dc2b7d88e5'
down_revision: Union[str, None] = '9dd4c958be21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('channel_categories_category_id_fkey', 'channel_categories', type_='foreignkey')
    op.drop_constraint('channel_categories_channel_id_fkey', 'channel_categories', type_='foreignkey')
    op.create_foreign_key(None, 'channel_categories', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'channel_categories', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'channel_categories', type_='foreignkey')
    op.drop_constraint(None, 'channel_categories', type_='foreignkey')
    op.create_foreign_key('channel_categories_channel_id_fkey', 'channel_categories', 'channels', ['channel_id'], ['id'])
    op.create_foreign_key('channel_categories_category_id_fkey', 'channel_categories', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
