"""Update datetime columns to timezone aware

Revision ID: 3f4f352bfe9c
Revises: d125a1aa2c7c
Create Date: 2025-01-14 12:07:28.823516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f4f352bfe9c'
down_revision: Union[str, None] = 'd125a1aa2c7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
