"""Add feed_articles junction table typo fix

Revision ID: 6aacfa497b39
Revises: dd4d8e6c802f
Create Date: 2025-01-14 14:05:56.131566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aacfa497b39'
down_revision: Union[str, None] = 'dd4d8e6c802f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('articles_feed_id_fkey', 'articles', type_='foreignkey')
    op.drop_column('articles', 'feed_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('feed_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('articles_feed_id_fkey', 'articles', 'feeds', ['feed_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
