"""update video channel thumbnail url column name

Revision ID: 8037c0ca804e
Revises: facd1419613b
Create Date: 2025-02-17 15:05:01.421287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8037c0ca804e'
down_revision: Union[str, None] = 'facd1419613b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('thumbnail_url', sa.String(), nullable=True))
    op.drop_column('channels', 'thumbnail')
    op.add_column('videos', sa.Column('thumbnail_url', sa.String(), nullable=True))
    op.drop_column('videos', 'thumbnail')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('thumbnail', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('videos', 'thumbnail_url')
    op.add_column('channels', sa.Column('thumbnail', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('channels', 'thumbnail_url')
    # ### end Alembic commands ###
