"""channel handle 2

Revision ID: 833bd3397bd0
Revises: b474d1d5ed82
Create Date: 2025-03-10 16:12:37.901441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '833bd3397bd0'
down_revision: Union[str, None] = 'b474d1d5ed82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('handle', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'handle')
    # ### end Alembic commands ###
