"""channeld elete

Revision ID: 9dd4c958be21
Revises: 7df13fb03742
Create Date: 2025-03-13 18:07:07.156131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd4c958be21'
down_revision: Union[str, None] = '7df13fb03742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('videos_channel_id_fkey', 'videos', type_='foreignkey')
    op.create_foreign_key(None, 'videos', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.create_foreign_key('videos_channel_id_fkey', 'videos', 'channels', ['channel_id'], ['id'])
    # ### end Alembic commands ###
