"""Add videos and channels tables for real this time

Revision ID: facd1419613b
Revises: 7d984b1d0969
Create Date: 2025-02-17 15:02:16.836709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'facd1419613b'
down_revision: Union[str, None] = '7d984b1d0969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
